// ─── GROUNDFLOOR MOCK DATA ───────────────────────────────────────────────────

const STAGES = ['Idea', 'Pre-seed', 'Seed', 'Series A'];
const INDUSTRIES = ['FinTech', 'HealthTech', 'SaaS', 'AI/ML', 'CleanTech', 'EdTech', 'Marketplace', 'Consumer'];

const PITCHES = [
  {
    id: 'p001',
    founder: {
      name: 'Maya Chen',
      initials: 'MC',
      avatar: null,
      color: '#E85D04',
      location: 'San Francisco, CA',
      bio: 'Ex-Stripe. Building the future of SMB lending.',
    },
    problem: 'Small businesses wait 47 days on average to get approved for a loan — and 60% are rejected without explanation.',
    solution: 'We underwrite SMB loans in 4 minutes using real-time cash flow data instead of credit scores.',
    industry: 'FinTech',
    stage: 'Pre-seed',
    postedAt: new Date(Date.now() - 2 * 60 * 60 * 1000), // 2h ago
    upvotes: 247,
    comments: 38,
    aiScore: {
      overall: 84,
      clarity: 91,
      marketSize: 88,
      differentiation: 79,
      founderMarketFit: 85,
      conviction: 77,
      fatalFlaw: 'Loan defaults during economic downturns could wipe out the business before you hit profitability.',
      strongestSignal: 'The 4-minute underwriting using live cash flow data is genuinely defensible if the data moat is real.',
      investorQuestion: 'What is your default rate, and how does it compare to traditional lenders?',
    },
    trending: true,
    hallOfFame: true,
    todayRank: 1,
    risingScore: 98,
  },
  {
    id: 'p002',
    founder: {
      name: 'James Okafor',
      initials: 'JO',
      avatar: null,
      color: '#7209B7',
      location: 'Lagos, Nigeria',
      bio: 'Doctor turned founder. 2x exit. Obsessed with healthcare access in Africa.',
    },
    problem: 'In sub-Saharan Africa, 70% of patients travel over 2 hours to see a specialist, and most die before they arrive.',
    solution: 'A voice-first AI triage tool that works on $20 feature phones, routes patients to the nearest available specialist.',
    industry: 'HealthTech',
    stage: 'Seed',
    postedAt: new Date(Date.now() - 5 * 60 * 60 * 1000),
    upvotes: 412,
    comments: 67,
    aiScore: {
      overall: 91,
      clarity: 95,
      marketSize: 93,
      differentiation: 89,
      founderMarketFit: 98,
      conviction: 82,
      fatalFlaw: 'Regulatory approval in 50+ countries is a 5-year problem, not a feature sprint.',
      strongestSignal: 'Founder-market fit is off the charts — a doctor who lived this problem building for a market he understands intimately.',
      investorQuestion: 'How do you navigate the liability when the AI makes a wrong triage call?',
    },
    trending: true,
    hallOfFame: true,
    todayRank: 2,
    risingScore: 95,
  },
  {
    id: 'p003',
    founder: {
      name: 'Sara Kim',
      initials: 'SK',
      avatar: null,
      color: '#0077B6',
      location: 'Seoul, South Korea',
      bio: 'Product @ Kakao. Building tools for creators who are tired of the algorithm.',
    },
    problem: 'Content creators earn 0.3 cents per stream but need 1M streams just to cover rent in a major city.',
    solution: 'A fan subscription platform where creators sell access to their creative process, not just the final output.',
    industry: 'Consumer',
    stage: 'Idea',
    postedAt: new Date(Date.now() - 8 * 60 * 60 * 1000),
    upvotes: 189,
    comments: 44,
    aiScore: {
      overall: 67,
      clarity: 82,
      marketSize: 71,
      differentiation: 54,
      founderMarketFit: 72,
      conviction: 56,
      fatalFlaw: 'Patreon and Substack already own this space. The differentiation of "process vs. output" is not enough to break switching costs.',
      strongestSignal: 'The problem is real and emotionally resonant — the monetization gap for mid-tier creators is genuinely underserved.',
      investorQuestion: 'What does this product do that Patreon cannot copy in a single product update?',
    },
    trending: false,
    hallOfFame: false,
    todayRank: 3,
    risingScore: 62,
  },
  {
    id: 'p004',
    founder: {
      name: 'Dmitri Volkov',
      initials: 'DV',
      avatar: null,
      color: '#2D6A4F',
      location: 'Berlin, Germany',
      bio: 'Climate scientist → founder. 10 years studying carbon, now building the fix.',
    },
    problem: 'Companies spend $2.3B/year on carbon offset certificates that are fraudulent or unverifiable.',
    solution: 'We use satellite imagery + ML to verify carbon sequestration in real time before any certificate is issued.',
    industry: 'CleanTech',
    stage: 'Pre-seed',
    postedAt: new Date(Date.now() - 18 * 60 * 60 * 1000),
    upvotes: 334,
    comments: 51,
    aiScore: {
      overall: 88,
      clarity: 87,
      marketSize: 90,
      differentiation: 92,
      founderMarketFit: 94,
      conviction: 78,
      fatalFlaw: 'The sales cycle to large corporates buying offsets is 12-18 months. You will run out of runway before deals close.',
      strongestSignal: 'The satellite + ML verification layer is genuinely novel and the fraud problem is massive and documented.',
      investorQuestion: 'Do you have any LOIs from buyers already, and how are you thinking about the enterprise sales motion?',
    },
    trending: true,
    hallOfFame: true,
    todayRank: 4,
    risingScore: 88,
  },
  {
    id: 'p005',
    founder: {
      name: 'Priya Nair',
      initials: 'PN',
      avatar: null,
      color: '#C77DFF',
      location: 'Bangalore, India',
      bio: 'Engineer @ Razorpay. First-time founder. Building what I needed 3 years ago.',
    },
    problem: 'Junior engineers at Indian tech companies have zero visibility into whether they are being underpaid by 20-80%.',
    solution: 'An anonymous salary benchmarking tool that generates a real-time market report in 90 seconds using verified peer data.',
    industry: 'SaaS',
    stage: 'Idea',
    postedAt: new Date(Date.now() - 3 * 60 * 60 * 1000),
    upvotes: 156,
    comments: 29,
    aiScore: {
      overall: 72,
      clarity: 89,
      marketSize: 68,
      differentiation: 61,
      founderMarketFit: 80,
      conviction: 63,
      fatalFlaw: 'Levels.fyi and LinkedIn Salary already own this in India. Distribution is the problem, not the product.',
      strongestSignal: 'The 90-second result is a real differentiator — most tools require you to submit and wait. Instant gratification matters.',
      investorQuestion: 'How do you get the initial data to make the benchmarks credible before you have enough users?',
    },
    trending: false,
    hallOfFame: false,
    todayRank: 5,
    risingScore: 74,
  },
  {
    id: 'p006',
    founder: {
      name: 'Alex Rivera',
      initials: 'AR',
      avatar: null,
      color: '#F72585',
      location: 'Austin, TX',
      bio: 'HS teacher → EdTech founder. My students gave me the idea.',
    },
    problem: 'High school students in underserved districts have no structured way to discover or apply for local trade apprenticeships.',
    solution: 'A TikTok-style platform where local trades businesses post 30-second job previews and students swipe to apply instantly.',
    industry: 'EdTech',
    stage: 'Pre-seed',
    postedAt: new Date(Date.now() - 31 * 60 * 60 * 1000),
    upvotes: 298,
    comments: 55,
    aiScore: {
      overall: 79,
      clarity: 84,
      marketSize: 76,
      differentiation: 78,
      founderMarketFit: 88,
      conviction: 71,
      fatalFlaw: 'The two-sided marketplace cold start problem is brutal here — you need both students and businesses before either side has value.',
      strongestSignal: 'The format insight is sharp: trades businesses do not know how to recruit Gen Z, and TikTok-style video solves exactly that.',
      investorQuestion: 'What is your plan to seed supply on the business side before you have student demand?',
    },
    trending: true,
    hallOfFame: false,
    todayRank: 6,
    risingScore: 81,
  },
  {
    id: 'p007',
    founder: {
      name: 'Tom Wei',
      initials: 'TW',
      avatar: null,
      color: '#FFB703',
      location: 'New York, NY',
      bio: '3x founder. Last company acquired by Shopify. Now solving enterprise AI adoption.',
    },
    problem: 'Fortune 500 companies spend 18 months and $4M deploying off-the-shelf AI tools that employees refuse to use.',
    solution: 'We deploy AI copilots inside existing enterprise workflows in 2 weeks with guaranteed 80% adoption or money back.',
    industry: 'AI/ML',
    stage: 'Series A',
    postedAt: new Date(Date.now() - 72 * 60 * 60 * 1000),
    upvotes: 521,
    comments: 92,
    aiScore: {
      overall: 93,
      clarity: 96,
      marketSize: 95,
      differentiation: 88,
      founderMarketFit: 97,
      conviction: 90,
      fatalFlaw: 'The "money back guarantee" is a sales tactic, not a moat. A well-funded competitor can copy this instantly.',
      strongestSignal: 'Founder has done it before in adjacent space. The 2-week deployment claim, if defensible, kills every incumbent's pitch.',
      investorQuestion: 'What specifically makes 2-week deployment possible when Accenture charges $4M for 18 months?',
    },
    trending: false,
    hallOfFame: true,
    todayRank: 7,
    risingScore: 77,
  },
  {
    id: 'p008',
    founder: {
      name: 'Zara Ahmed',
      initials: 'ZA',
      avatar: null,
      color: '#06D6A0',
      location: 'Dubai, UAE',
      bio: 'Logistics nerd. 8 years in supply chain at DHL. First startup.',
    },
    problem: 'E-commerce brands in MENA lose 23% margin to last-mile delivery failures and cannot predict which shipments will fail.',
    solution: 'Predictive logistics software that flags high-risk deliveries 48 hours in advance so brands can pre-emptively reroute.',
    industry: 'Marketplace',
    stage: 'Seed',
    postedAt: new Date(Date.now() - 4 * 60 * 60 * 1000),
    upvotes: 203,
    comments: 33,
    aiScore: {
      overall: 82,
      clarity: 88,
      marketSize: 84,
      differentiation: 80,
      founderMarketFit: 87,
      conviction: 74,
      fatalFlaw: 'Your biggest risk is data access — you need carrier data to train the model, and carriers have zero incentive to share it.',
      strongestSignal: '23% margin loss is a screaming pain point. Any brand losing that much on logistics will take a meeting immediately.',
      investorQuestion: 'How do you get the carrier data to make your predictions accurate before you have a commercial deal with them?',
    },
    trending: true,
    hallOfFame: false,
    todayRank: 8,
    risingScore: 86,
  }
];

const WEEKLY_DROP = [
  PITCHES[1], // James Okafor
  PITCHES[0], // Maya Chen
  PITCHES[3], // Dmitri Volkov
  PITCHES[6], // Tom Wei
  PITCHES[5], // Alex Rivera
];

const SAMPLE_COMMENTS = {
  p001: [
    { id: 'c1', author: 'Morgan T.', role: 'Investor', roleColor: '#FFB703', text: 'Have seen 3 companies attempt this. The underwriting model is the entire business — what data providers are you using?', time: '1h ago', upvotes: 24 },
    { id: 'c2', author: 'Rachel S.', role: 'Operator', roleColor: '#E85D04', text: 'Built credit models at Capital One for 6 years. The hardest part is not the underwriting, it\'s fraud at the top of the funnel. How are you handling identity verification?', time: '45m ago', upvotes: 31 },
    { id: 'c3', author: 'Dave K.', role: 'Potential Customer', roleColor: '#06D6A0', text: 'I own 3 restaurants. I would literally sign up today. The 47-day wait is killing us.', time: '30m ago', upvotes: 47 },
    { id: 'c4', author: 'Anjali P.', role: 'Founder', roleColor: '#C77DFF', text: 'How are you thinking about geographic expansion? US regulatory environment for lending is a nightmare state-by-state.', time: '15m ago', upvotes: 12 },
  ],
};

window.GROUNDFLOOR_DATA = { PITCHES, STAGES, INDUSTRIES, WEEKLY_DROP, SAMPLE_COMMENTS };
